name: 1password
base: core20
version: "0.8.0-22506"
summary: A secure password manager
description: |
  1Password saves all your passwords and encrypts them with your
  Master Password – which only you know. To sign in to an account,
  just click or tap to fill your details with 1Password.

grade: devel
confinement: devmode

architectures: [amd64]

apps:
  1password:
    command: opt/1Password/1password
    desktop: usr/share/applications/1password.desktop
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  1password:
    plugin: dump
    source: https://onepassword.s3.amazonaws.com/linux/debian/pool/main/1/1password/1password-0.8.0.22506.deb
    source-type: deb
    stage-packages:
      - gconf2
      - gconf-service
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libcurl4
      - libc6
      - libgtk-3-0
      - libc-dev
      - libxss-dev
      - libx11-xcb1
      - libasound2
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
    override-pull: |
      snapcraftctl pull

      sed -i 's|Exec=.*|Exec=1password %U|g' usr/share/applications/1password.desktop

      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/1password.png|g' \
        usr/share/applications/1password.desktop
